from __future__ import annotations

from typing import Protocol


class VcsClient(Protocol):
    async def clone(self, repo_full_name: str, ref: str, dest: str) -> str: ...
    async def create_branch(self, workdir: str, branch: str) -> None: ...
    async def commit_all(
        self, workdir: str, message: str, paths: list[str] | None = None
    ) -> str: ...
    async def push(self, workdir: str, branch: str) -> None: ...
    async def open_pr(
        self, repo_full_name: str, head: str, base: str, title: str, body: str, draft: bool
    ) -> str: ...
